language: python
python:
  - 2.7
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.14
  - DJANGO=1.9.9
  - DJANGO=1.10.0
install:
    - pip install -q Django==$DJANGO
    - pip install -r requirements.txt
script:
    - rm fabfile.py
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=django_cbtp_email --cover-tests --cover-erase --with-doctest --nocapture
after_success:
    - coveralls
notifications:
    email: false
