language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
env:
  - DJANGO="Django<1.9"   # Django 1.8.x  (LTS version)  |   2.7, 3.2 (until the end of 2016), 3.3, 3.4, 3.5
  - DJANGO="Django<1.10"  # Django 1.9.x                 |   2.7, 3.4, 3.5
  - DJANGO="Django<1.11"  # Django 1.10.x                |   2.7, 3.4, 3.5
  - DJANGO="Django<2.0"   # Django 1.11.x (LTS version)  |   2.7, 3.4, 3.5, 3.6
install:
    - pip install --quiet --upgrade -r requirements.txt
    - pip install --quiet --upgrade setuptools wheel
    - pip install --quiet --upgrade "$DJANGO"
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=django_cbtp_email --cover-tests --cover-erase --with-doctest --nocapture
after_success:
    - coveralls
notifications:
    email: false
